name: Build Windows Exe

on:
  push:
    tags:
      - 'v*' # Si attiva quando crei una release con tag tipo v1.0.1

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 requests pyinstaller

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --noconfirm --onefile --windowed --add-data "frasi.json;." --add-data "images;images" --add-data "sound;sound" --name "GiraLaRuota_v1.0.1" main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: GiraLaRuota-Windows
        path: dist/GiraLaRuota_v1.0.1.exe

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/GiraLaRuota_v1.0.1.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
