name: Build Windows EXE Automatic

on:
  workflow_dispatch:  # build manuale quando vuoi

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller requests PyQt5

      - name: Read version from Python file
        id: get_version
        run: |
          $version = (Select-String -Path "ruota_fortuna.py" -Pattern 'VERSION_ATTUALE\s*=\s*"(.*)"').Matches[0].Groups[1].Value
          echo "VERSION=$version" >> $env:GITHUB_ENV

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --windowed --name "RuotaDellaFortuna_${{ env.VERSION }}" --icon "images/logo.ico" --add-data "images;images" --add-data "sound;sound" --add-data "frasi.json;." ruota_fortuna.py

      - name: Upload EXE to existing Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ env.VERSION }}"
          files: "dist/RuotaDellaFortuna_${{ env.VERSION }}.exe"
